version: '3'

services:
  fastapi-app:
    image: dekardar/terraform-aws:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - AWS_DEFAULT_REGION=us-west-1
